#!/usr/bin/env python3
r"""fix_tables.py — Post-process pandoc LaTeX output to add booktabs row styling.

Usage:
    python scripts/fix_tables.py paper/paper.tex [--inplace]

Reads a .tex file generated by pandoc 3.x (which already uses \toprule/\midrule/\bottomrule),
and adds:
  - \rowcolor{gray!14} before header row (after \toprule)
  - \rowcolors{2}{gray!5}{white} after \endlastfoot (start of body rows)
  - Strips superfluous \noalign{} groups

Works with both {longtable} and {tabular} environments.
"""

from __future__ import annotations
import re
import sys


def fix_tables(tex: str) -> str:
    """Apply row-coloring improvements to all table environments in tex source."""

    # Work on longtable and tabular environments
    # Strategy: process each environment block individually

    def _fix_longtable(m: re.Match[str]) -> str:
        block = m.group(0)
        # Determine which environment we're in
        is_longtable = "\\begin{longtable}" in block
        env = "longtable" if is_longtable else "tabular"
        env_end = f"\\end{{{env}}}"

        # --- 1. Add \rowcolor before header row (after \toprule) ---
        # Pattern: \toprule\noalign{} → \toprule\noalign{}\rowcolor{gray!14}
        block = re.sub(
            r"(\\toprule\s*\\noalign\{\}\s*)(?=\\begin\{minipage\}|[^\n])",
            r"\1\\rowcolor{gray!14}\n",
            block,
        )

        # --- 2. Add \rowcolors after \endlastfoot (for longtable) ---
        # \rowcolors must go AFTER the footer definition, at start of body rows
        if is_longtable:
            block = re.sub(
                r"(\\endlastfoot\s*)",
                r"\1\\rowcolors{2}{gray!5}{white}\n",
                block,
            )
        else:
            # For tabular: add \rowcolors after \midrule
            # The structure is: \toprule\n header\\ \midrule\n body
            block = re.sub(
                r"(\\midrule\s*)(?=\\bottomrule)",
                r"\1\\rowcolors{2}{gray!5}{white}\n",
                block,
            )

        # --- 3. Strip superfluous \noalign{} after \midrule ---
        # Keep it after \toprule (needed for \rowcolor to work correctly) but
        # remove after \midrule and \bottomrule for cleanliness
        block = block.replace("\\midrule\\noalign{}", "\\midrule")
        block = block.replace("\\bottomrule\\noalign{}", "\\bottomrule")

        # --- 4. Tighten spacing within tables ---
        # Add \small if not already present
        # (Our Lua filter handles this, so this is a fallback)
        if "\\small" not in block and is_longtable:
            # Inject \small before the first line of the environment
            block = re.sub(
                r"(\\\\begin\{longtable\})",
                r"{\\small\n\1",
                block,
            )

        return block

    # Apply to all longtable environments
    result = re.sub(
        r"\\begin\{longtable\}.*?\\end\{longtable\}",
        _fix_longtable,
        tex,
        flags=re.DOTALL,
    )

    # Apply to tabular environments (usually not generated by pandoc 3.x)
    result = re.sub(
        r"\\begin\{tabular\}.*?\\end\{tabular\}",
        _fix_longtable,
        result,
        flags=re.DOTALL,
    )

    return result


def main() -> None:
    args = sys.argv[1:]
    if not args:
        print("Usage: python fix_tables.py paper.tex [--inplace]", file=sys.stderr)
        sys.exit(1)

    path = args[0]
    inplace = "--inplace" in args

    with open(path, "r", encoding="utf-8") as f:
        original = f.read()

    fixed = fix_tables(original)

    if inplace:
        with open(path, "w", encoding="utf-8") as f:
            f.write(fixed)
        print(f"Fixed tables in {path}")
    else:
        out_path = path.replace(".tex", "-fixed.tex")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(fixed)
        print(f"Written to {out_path}")

    # Stats
    lt_before = len(re.findall(r"\\begin\{longtable\}", original))
    lt_after = len(re.findall(r"\\begin\{longtable\}", fixed))
    rowcolors_count = len(re.findall(r"\\rowcolors", fixed))
    print(f"  longtables: {lt_before} → {lt_after}")
    print(f"  rowcolors added: {rowcolors_count}")


if __name__ == "__main__":
    main()
